### ISSUE TITLE
terminating connection because of crash of another server process

### ISSUE THREAD

**Issue by gonick** [openmaptiles/openmaptiles#937] opened 2020-06-20 13:39 UTC
```
psql:/sql/parallel/housenumber.sql:21:psql:/sql/parallel/poi.sql:167: WARNING:  terminating connection because of crash of another server process


*** WARNING detected, aborting
Makefile:327: recipe for target 'import-sql' failed
make: *** [import-sql] Error 1
```

It keeps on failing at this import

**Comment by arichnad** [comment] 2020-06-22 18:18
This might be the same as my issue #938.  Can you run this and see if it says "Killed" in it?  `docker logs openmaptiles_postgres_1 |grep Killed`

Thanks.

**Comment by gonick** [comment] 2020-06-24 10:17
Yes It says Killed

**Comment by gonick** [comment] 2020-06-24 10:18
LOG:  server process (PID 22145) was terminated by signal 9: Killed
LOG:  server process (PID 22749) was terminated by signal 9: Killed

LOG:  server process (PID 22145) was terminated by signal 9: Killed
DETAIL:  Failed process was running: CREATE MATERIALIZED VIEW osm_transportation_merge_linestring AS (
	    SELECT
	        (ST_Dump(geometry)).geom AS geometry,
	        NULL::bigint AS osm_id,
	        highway, construction,
	        z_order
	    FROM (
	      SELECT
	          ST_LineMerge(ST_Collect(geometry)) AS geometry,
	          highway, construction,
--
	  SET geometry =
	           CASE WHEN ST_NPoints(ST_ConvexHull(geometry))=ST_NPoints(geometry)
	           THEN ST_Centroid(geometry)
	           ELSE ST_PointOnSurface(geometry)
	    END
	  WHERE ST_GeometryType(geometry) <> 'ST_Point'"
	PL/pgSQL function convert_housenumber_point() line 3 at SQL statement
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2020-06-19 13:21:15 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 4B/B807F790
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
LOG:  redo done at 4B/D97FDFC0
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  server process (PID 22749) was terminated by signal 9: Killed
DETAIL:  Failed process was running: CREATE MATERIALIZED VIEW osm_transportation_merge_linestring AS (
	    SELECT
	        (ST_Dump(geometry)).geom AS geometry,
	        NULL::bigint AS osm_id,
	        highway, construction,
	        z_order
	    FROM (
	      SELECT
	          ST_LineMerge(ST_Collect(geometry)) AS geometry,
	          highway, construction,

**Comment by arichnad** [comment] 2020-06-25 18:17
Hmmm, I thought we were seeing the same problem but I'm not so sure anymore.  We do both see "Killed" in postgres, but you're seeing it in create view osm_transportation_merge_linestring (issue 937) and I'm seeing it in create view osm_building_block_gen1 (issue 938).

**Comment by Proxipy** [comment] 2020-06-30 20:59
i'm seeing a similar issue when running quickstart.sh

psql:psql:/sql/parallel/building.sql:82:psql:/sql/parallel/transportation__transportation_name.sql:1129:  server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
psql:/sql/parallel/building.sql:82: fatal: connection to server was lost
psql:/sql/parallel/water__waterway.sql:22: WARNING:  terminating connection because of crash of another server process

*** WARNING detected, aborting
make: *** [makefile:357: import-sql] Error 1]

Not sure if I should add here, or create a new issue

**Comment by arichnad** [comment] 2020-07-01 02:09
@proxipy Nice, thanks for the report.  Have you tested the previous version?  6ac544f?  Does that work for you?  Thanks!

**Comment by Proxipy** [comment] 2020-07-01 11:32
@arichnad This is the first time I ever tried this piece of software. Haven't tried previous versions. I did however trace my problem back to a memory issue. Using dmesg in the terminal revealed that Ubuntu killed the postgres container due to "out of memory". I upped the available RAM on my VPS and tried again. This time successfull. If this wasn't an issue in any previous version then maybe a memory leak got introduced somewhere.

**Comment by arichnad** [comment] 2020-07-01 14:14
@Proxipy Right, I understand, thank you.  It's interesting that changing the amount of RAM worked for you!  What did you change it from and what did you change it to?

Also, can you tell me if your postgres docker log (docker logs openmaptiles_postgres_1 2>&1 |grep Failed) mentions "Failed process was running: CREATE MATERIALIZED VIEW osm_transportation_merge_linestring" (this ticket) *OR* does it mention "Failed process was running: CREATE MATERIALIZED VIEW osm_building_block_gen1" (ticket 938) ?  Thanks.

**Comment by Proxipy** [comment] 2020-07-01 20:04
@arichnad I changed the amount of ram from 4gb to 8gb. I had't read the quickstart.md which actually suggests having 8gb or more, even for smaller extracts. So the problem could've well been on my end for not meeting the minimum requirements. I am however scaling op my attempts, first generating tiles beyond zoomlevel 7, then on to bigger extracts. If I run into the mentioned problem again i will try both your commands and see what it says (and report back ofcourse).

**Comment by TomPohys** [comment] 2020-09-22 11:54
Hi @gonick, it is possible to close this issue, when the `terminating connection because of crash of another server process` was caused by a low amount of RAM or SWAP?

**Closed** 2020-10-12 14:45 UTC
