### ISSUE TITLE
admin_level=4 no longer showing at higher zoom levels

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#1276] opened 2021-10-24 18:01 UTC
Since fix #1213 `admin_level=4` is no longer shown at higher zoom levels. This means that US State borders don't show when zooming in, and only show on zoom levels 1-4.

![missing](https://user-images.githubusercontent.com/30858/138606360-ef06bee0-c212-408f-af93-3109b5084844.png)

This seems to be the same/similar issue that #1260 was addressing.

**Comment by RS974** [comment] 2021-11-16 11:08
I merged several PBF files from France and border countries.
new server installation from 15 November
```
git clone https://github.com/openmaptiles/openmaptiles.git
cd openmaptiles
make
./quickstart.sh merged-file
```

The border between France and Spain disappears after zoom 4 #1276

All zoom in the Atlantic or the Mediterranean, the borders for France, Corsica and Spain are missing #1260

![OMS_2021-11-16_11-30-16](https://user-images.githubusercontent.com/23738457/141973005-0920bd07-9947-4ae6-9ca9-d63decf139eb.png)

**Comment by ZeLonewolf** [comment] 2023-02-01 23:09
I am not seeing this issue on planet builds:

https://zelonewolf.github.io/openstreetmap-americana/#map=4/42.33/1.6

**Comment by TomPohys** [comment] 2023-03-13 10:31
Hi @nnhubbard, As @ZeLonewolf  mention, the `us-northeast` works fine (I also test it). So the Connecticut extract clips the border data.

**Comment by TomPohys** [comment] 2023-03-13 10:33
Hi @RS974, this could be caused by merging pbfs. Are the borders correctly imported into the database?

**Comment by TomPohys** [comment] 2023-04-18 05:19
As `us-northeast` works fine, probably not a problem with OpenMapTiles.

**Closed by TomPohys** 2023-04-18 05:19 UTC
