### ISSUE TITLE
building aggregation fails with GEOSUnaryUnion: TopologyException

### ISSUE THREAD

**Issue by hpn0t0ad** [openmaptiles/openmaptiles#1058] opened 2020-12-25 22:20 UTC
Hi, I'm trying to generate a planet tileset up to z14, however it seems I can't even get past `import-sql` since I've run into various problems related to `osm_building_block_gen1()`.

I initially used v3.12, where `make import-sql` fails with the following error:
```
psql:/sql/parallel/building.sql:100: ERROR:  GEOSUnaryUnion: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -8539739.7009410355 4727139.8920735931 at -8539739.7009410355 4727139.8920735931
CONTEXT:  PL/pgSQL function osm_building_block_gen1() line 14 at FOR over SELECT rows
```

After that, I went back to 24b9328a5f47ad5273495ffc26fcff39c03794cd, because I figured there might have been some issue with #1044. Perhaps unsurprisingly, I got the following error:
```
psql:/sql/parallel/building.sql:82: ERROR:  invalid memory alloc request size 3427966716
CONTEXT:  PL/pgSQL function osm_building_block_gen1() line 6 at FOR over SELECT rows
```

I'm currently running 6ac544fc9610b57fb3041eebd725211ec154885c and it seems to be working fine so far (transportation isn't finished yet). However, I feel like I'm missing out on the latest features ;). Speaking of, what exactly are the benefits of building aggregation anyway? If it leads to smaller MVT data, I'd very much appreciate some hints on how to get this working.

(I tested two different pbfs, planet-201214 and planet-201130, I haven't made any changes except for removing some layers I don't need from openmaptiles.yaml. My system has a few E7-4890v2 and 1TB RAM)

**Comment by suur** [comment] 2020-12-26 14:21
Similar issue at https://github.com/openmaptiles/openmaptiles/issues/1022

I ran into the same issue, but was able to import the whole planet (without ST_MakeValid) by using Postgres 9.6, PostGIS 3.1 and GEOS 3.9.0. The updated PostGIS/GEOS combo can handle the topology exceptions, but you need to build a custom docker image.

**Comment by hpn0t0ad** [comment] 2020-12-28 00:37
Brilliant! Importing the building layer just completed without issue using your GEOS 3.9 Postgres container (in about 15 hours - which is probably reasonable since other layers took longer).
So thanks a lot for your help! Hope the openmaptiles/postgis image will be updated before long.

**Comment by skylarmt** [comment] 2021-01-31 02:55
>Hope the openmaptiles/postgis image will be updated before long.

Checking in, seems nobody's updated anything yet...

**Comment by StephenAtty** [comment] 2021-02-13 16:15
I've just tripped over this issue too

**Comment by Yermo** [comment] 2021-02-16 21:36
I am also running into this issue.

Ubuntu Server 20.04LTS.

```
-------------------------------------------------------------------------------------
====> : OpenMapTiles quickstart! [ https://github.com/openmaptiles/openmaptiles ]    
      : This will be logged to the ./quickstart.log file (for debugging) and to the screen
      : Area             : maryland 
      : Download server  : unset (automatic) 
      : Preloaded image  :  
      : Git version      : d69ae015ad80794656c3460d7a15ccb436cb1575 
      : Started          : 2021-02-16T21:14+0000 
      : Your bash version: 5.0.17(1)-release
      : Your OS          : linux-gnu
Docker version 19.03.13, build cd8016b6bc
docker-compose version 1.25.5, build unknown
 
-------------------------------------------------------------------------------------
      : This is working on x86_64 ; Your kernel is:
5.4.0-65-generic
x86_64
      : --- Memory, CPU info ---- 
System memory (GB): 629.8714
SwapTotal:       8388604 kB
CPU number: 48 x bogomips	: 4400.37
MemFree:        626656228 kB
SwapFree:        8388604 kB
CmaFree:               0 kB
HugePages_Free:        0
```

```
$ sudo ./quickstart.sh --empty maryland
```
yields:
```
psql:/sql/parallel/building.sql:100: ERROR:  GEOSUnaryUnion: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -8539739.7009410355 4727139.8920735931 at -8539739.7009410355 4727139.8920735931
CONTEXT:  PL/pgSQL function osm_building_block_gen1() line 14 at FOR over SELECT rows
Time: 319480.436 ms (05:19.480)
xargs: sh: exited with status 255; aborting
make: *** [Makefile:397: import-sql] Error 124
```

**Comment by carlos-vl** [comment] 2021-02-18 07:35
I am also having this issue.
It would be great if you could indicate how to modify the `docker-compose.yml` to use the docker container proposed by @suur , so that `quickstart.sh`  can finish.
After replacing the docker container for postgres do I need to restart the import or can I use any specific command to continue from where the error happened?

Thanks a lot!

**Comment by esgn** [comment] 2021-03-01 07:24
Got the same error this morning. Will be relaunching data integration with @suur image.
Regarding the `docker-compose.yml` here is mine if it helps @carlos-vl 
```  
postgres:
    build:
      context: ./docker-postgis
    image: openmaptiles/postgis:updated_by_suur
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - postgres_conn
    ports:
      - "5432"
    env_file: .env-postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
```
You can ignore the `command` and `my-postgres-conf` lines. I'm just passing a custom configuration to postgres to speed up calculations.

**Comment by Yermo** [comment] 2021-03-01 20:19
@esgn I would be curious to hear how you are speeding up calculations.

**Comment by jianxu99** [comment] 2021-03-19 21:35
I have the error. How exactly to use the docker from @suur  ?

psql:/sql/parallel/building.sql:100: ERROR:  GEOSUnaryUnion: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -8539739.7009410355 4727139.8920735931 at -8539739.7009410355 4727139.8920735931
CONTEXT:  PL/pgSQL function osm_building_block_gen1() line 14 at FOR over SELECT rows

**Comment by StephenAtty** [comment] 2021-03-21 13:33
Is there going to be an official fix for this?

**Comment by TomPohys** [comment] 2021-03-22 10:42
Hi all, thank you for the discussion, and a big thanks to @suur for his fix. I create PR (https://github.com/openmaptiles/openmaptiles-tools/pull/340) and if everything is OK, it can be merge.

**Comment by nabla1** [comment] 2021-03-22 17:53
@TomPohys 
May I know when the fix can be merged? Thanks.

**Comment by etresoft** [comment] 2021-04-14 01:37
I'm confused. What this fix reverted?

**Comment by ache051** [comment] 2021-04-15 03:32
@etresoft Seems the maintainers would rather have docker-postgis folks to update their base image(s) with newer version of GEOS than grafting it to the image afterward. Importing planet.osm.pbf now to see if it works...

**Comment by etresoft** [comment] 2021-04-15 14:22
> @etresoft Seems the maintainers would rather have docker-postgis folks to update their base image(s) with newer version of GEOS than grafting it to the image afterward. Importing planet.osm.pbf now to see if it works...

Yes. I realize that. I asked because my planet import failed due to this exact error. Someone claimed to have fixed it by updating both PostGIS and GEOS. So I updated my images and tried the buildings import again. It failed again. Then I saw that part of the fix was reverted. So was the fix reverted? Or was it something else?

I don't dispute that the PostGIS image should be updated. But that does not preclude this broken project from being updated too. It doesn't hurt anything if, in a few weeks, PostGIS gets updated, and then people spend another few weeks wasting 39 seconds re-applying an unnecessary GEOS update. That seems like a better approach that having people waste days trying a planet import that will never succeed.

**Comment by TomPohys** [comment] 2021-04-15 14:45
There was a revert commit of force upgrade of GEOS because in the meantime docker PostGIS 9.6-3.1 was updated (https://github.com/postgis/docker-postgis/commit/c58090124ccd7f54b39bb5bcf2f79b7011e94964) and I assumed based on hash code that was moved to GEOS 3.9.1. (based on `master` branch and https://github.com/postgis/docker-postgis/blob/9833646d5e311d8ef76acfb2b2f0ccb7a3c87e3c/12-master/Dockerfile#L97-L98). If not, let's force upgrade GEOS based on @suur suggestion.

I am sorry for the problems

**Comment by claustres** [comment] 2021-04-15 15:53
I can confirm that using the `latest` tag of openmaptiles-tools Docker images does not solve the problem so that the PostGIS upgrade does not seem to be sufficient.

**Comment by etresoft** [comment] 2021-04-15 15:56
I'm still trying to get my own Docker images to make it even that far. Open source is kind of like scientific research. If you can't replicate the results, then it doesn't actually qualify.

**Comment by nyurik** [comment] 2021-04-15 16:07
I think creating a pull request for the postgis/docker-postgis repo will get GEOS properly updated much faster than having a custom docker GEOS image override.  Are there any issues preventing this?

**Comment by etresoft** [comment] 2021-04-15 16:13
> I think creating a pull request for the [postgis/docker-postgis](https://github.com/postgis/docker-postgis) repo will get GEOS properly updated much faster than having a custom docker GEOS image override. Are there any issues preventing this?

Yes. The first step to any pull request is to make the change and validate on your own system. I'm trying to figure out why relation "ne_10m_admin_0_countries" does not exist. It makes it really difficult for people to participate in the project when they can't make even minor changes and test them. My task now is to remove this change to GEOS and see if I can import a small extract with my own, byte-for-byte identical forks.

**Comment by TomPohys** [comment] 2021-04-15 16:27
> 
> I'm trying to figure out why relation "ne_10m_admin_0_countries" does not exist. It makes it really difficult for people to participate in the project when they can't make even minor changes and test them. ...

"ne_10m_admin_0_countries" should be imported into PostGIS by `make import-data` (https://github.com/openmaptiles/openmaptiles-tools/blob/master/docker/import-data/clean-natural-earth.sh#L38)

**Comment by etresoft** [comment] 2021-04-15 16:34
> "ne_10m_admin_0_countries" should be imported into PostGIS by `make import-data` (https://github.com/openmaptiles/openmaptiles-tools/blob/master/docker/import-data/clean-natural-earth.sh#L38)

Yes. I realize that. I'm trying to figure out why that doesn't happen. Here is what I'm trying...
1. Try byte-for-byte fork of openmaptiles on PEI
2. Build my own images using byte-for-byte fork of openmaptiles-tools
3. Modify my fork of openmaptiles to use my images
4. If all that works, try it on Ontario
5. If that works, try it on planet
6. If all that works, no clue, but I guess I can proceed. If it doesn't work then at least I will have my own images where I can explore PostGIS/GEOS version, or maybe try ST_MakeValid

Any other suggestions?

**Comment by ache051** [comment] 2021-04-15 20:16
> If all that works, no clue, but I guess I can proceed. If it doesn't work then at least I will have my own images where I can explore PostGIS/GEOS version, or maybe try ST_MakeValid

FYI adding ST_MakeValid (https://github.com/manuelkasper/openmaptiles/commit/03b4c0e789558c1593f9ce2932a5b23c81e936a0) was the first thing I tried after failing to import planet initially, but it didn't work. Can also confirm that the latest openmaptiles-tools postgis image didn't fix the problem either. Is going to try @suur 's postgis build now.

**Comment by ache051** [comment] 2021-04-15 20:29
> There was a revert commit of force upgrade of GEOS because in the meantime docker PostGIS 9.6-3.1 was updated ([postgis/docker-postgis@c580901](https://github.com/postgis/docker-postgis/commit/c58090124ccd7f54b39bb5bcf2f79b7011e94964)) and I assumed based on hash code that was moved to GEOS 3.9.1. (based on `master` branch and https://github.com/postgis/docker-postgis/blob/c58090124ccd7f54b39bb5bcf2f79b7011e94964/13-master/Dockerfile#L97-L98). If not, let's force upgrade GEOS based on @suur suggestion.
> 
> I am sorry for the problems

It seems the GEOS update was only applied to PostGIS 12-master and 13-master builds. 9.6-3.1 wasn't updated :(

**Comment by etresoft** [comment] 2021-04-15 23:40
> FYI adding ST_MakeValid ([manuelkasper@03b4c0e](https://github.com/manuelkasper/openmaptiles/commit/03b4c0e789558c1593f9ce2932a5b23c81e936a0)) was the first thing I tried after failing to import planet initially, but it didn't work. Can also confirm that the latest openmaptiles-tools postgis image didn't fix the problem either. Is going to try @suur 's postgis build now.

A better idea would be to use ST_IsValid. This time I was able to build my own versions of openmaptiles-tools images with the updated GEOS and imported both PEI and Ontario. I just kicked off a planet import. If it fails again, I can develop a fix in my images now that they are working. Sadly, OSM has grown faster than my server budget. It will be a few days before I know more.

**Comment by tisis2** [comment] 2021-04-22 14:17
with the current release version i am heading also an error 124 when i try to generate north-america/us-south via quickstart.
is there a workaround to get that to run? im new to docker / docker-compose and did not get the workaround of @suur what it does and how i could apply it on my side. can anyone help me with this?

**Comment by etresoft** [comment] 2021-04-22 21:06
> with the current release version i am heading also an error 124 when i try to generate north-america/us-south via quickstart.
> is there a workaround to get that to run? im new to docker / docker-compose and did not get the workaround of @suur what it does and how i could apply it on my side. can anyone help me with this?

This might not be the most appropriate project to learn Docker with. Docker by itself can be extremely challenging. You can find any number of "learn Docker in 5 minute" tutorials, but being able to confidently make Docker do what you want may take you 5 months.

Basically, what you have to do is update the Docker images in openmaptiles-tools. At the very least, you will have to rebuild the postgis and postgis-preloaded. You can go to @suur's site listed above and get the Dockerfile. It should be easy to compare that file with the master see the section that was added. Then use "docker build -v -t openmaptiles-tools/postgis ." to generate your own image. Do the same with postgis-preloaded.

I think that will be all you need. I had another fix to generate-vectortiles, but that was incorporated into the master 6 days ago. I built my own versions of all of those images, for various reasons. You probably don't need that. But if you wanted to, you could change "openmaptiles-tools" to your own prefix, maybe upload them to Docker Hub, and reference those in your own fork of the "openmaptiles" project.

I still don't know if it will work. My import is still running. It hasn't crashed or run out of memory yet. It is on the last SQL phase. Waterway was completed. It must still be working on buildings.

**Comment by TomPohys** [comment] 2021-04-23 08:01
I am sorry for such a delay. Today was merged an update to GEOS 3.9.1 into OpenMapTiles-Tools. So if you change `TOOLS_VERSION` in `.env` to `latest` it will use a new updated version. 

You can also just change the [`docker-compose.yaml`](https://github.com/openmaptiles/openmaptiles/blob/76d5d753d8fae35e4d316f5532461835a3acf36b/docker-compose.yml#L14) to use just the latest PostGIS image and keep the versions of other images.

```diff
- 14 image: "${POSTGIS_IMAGE:-openmaptiles/postgis}:${TOOLS_VERSION}"
+ 14 image: "${POSTGIS_IMAGE:-openmaptiles/postgis}:latest"
```
However, this update to GEOS 3.9.1 does not bring the functions of GEOS 3.9.1 and just update already included functions in GEOS 3.7.1  - please read a discussion in https://github.com/postgis/docker-postgis/issues/233

**Comment by bricechart** [comment] 2021-05-01 23:55
> I am sorry for such a delay. Today was merged an update to GEOS 3.9.1 into OpenMapTiles-Tools. So if you change `TOOLS_VERSION` in `.env` to `latest` it will use a new updated version.
> 
> You can also just change the [`docker-compose.yaml`](https://github.com/openmaptiles/openmaptiles/blob/76d5d753d8fae35e4d316f5532461835a3acf36b/docker-compose.yml#L14) to use just the latest PostGIS image and keep the versions of other images.
> 
> ```diff
> - 14 image: "${POSTGIS_IMAGE:-openmaptiles/postgis}:${TOOLS_VERSION}"
> + 14 image: "${POSTGIS_IMAGE:-openmaptiles/postgis}:latest"
> ```
> 
> However, this update to GEOS 3.9.1 does not bring the functions of GEOS 3.9.1 and just update already included functions in GEOS 3.7.1 - please read a discussion in [postgis/docker-postgis#233](https://github.com/postgis/docker-postgis/issues/233)

I've updated my docker-compose.yml with the edits you suggestion and I'm still getting the TopologyException
![image](https://user-images.githubusercontent.com/28401828/116797742-2c114b00-aab7-11eb-8c42-cad80fc0a74c.png)

**Comment by ache051** [comment] 2021-05-03 01:31
@bricechart Same here. I am resolving back to graft on GEOS 3.9 and it works perfectly fine.

**Comment by etresoft** [comment] 2021-05-03 02:12
For the record, my forks successfully imported an entire planet. I have an AMD A8-7600 Radeon R7 with 32 GB RAM and a 2 TB SSD. It took 9.5 days for the import. I tried generating tiles too and got down to zoom 11 in 26.5 hours.

My goals were to:
1) establish that I could import a planet and serve similar vector data from commercial services, but without the licensing restrictions of openmaptiles or the riskiness of fly-by-night services; and
2) get some ballpark timings and disk usage requirements for eventually doing all this on AWS. 

Thanks to the openmaptiles and openmaptiles-tools projects, I was completely successful on both counts and got all the information I was looking for. It would be nice to see these projects kept more up-to-date. I'm skeptical about the old Postgres version and the note about ogr2ogr. Now that I have something that runs, I can work on updating those. I'm also interested in [this project](https://github.com/acalcutt/wdb-map-gen), which is an effort to de-dockerize all of this. At a minimum, it would be easy and beneficial to run a native DB, especially on AWS.

There have been some updates to the upstream versions since I started my run. I don't know how different they are. I would not merge any changes without reviewing each and every line.

**Comment by bricechart** [comment] 2021-05-03 10:38
> @bricechart Same here. I am resolving back to graft on GEOS 3.9 and it works perfectly fine.

What's the easiest way to force the importer to use GEOS 3.9?

**Comment by TomPohys** [comment] 2021-05-03 10:40
@bricechart if GEOS 3.9.1 is not suitable, let's downgrade GEOS to 3.9.0

**Comment by bricechart** [comment] 2021-05-03 10:53
@TomPohys How do I set things up to force the use of 3.9.0?

**Comment by TomPohys** [comment] 2021-05-03 11:34
If you would like to build your local docker then clone https://github.com/openmaptiles/openmaptiles-tools, change the GEOS version variable to 3.9.0 - https://github.com/openmaptiles/openmaptiles-tools/blob/master/docker/postgis/Dockerfile#L11. You can change a tag for your build in https://github.com/openmaptiles/openmaptiles-tools/blob/master/openmaptiles/__init__.py.

In OMT then you can check, if postgis is using correct GEOS by `make psql` and `SELECT postgis_full_version();`

**Comment by claustres** [comment] 2021-05-04 07:13
Follow up: I've succeeded in importing the planet DB simply using the latest tools version in my env file `TOOLS_VERSION=latest`. Not sure if it could be relevant but I've also used the latest v3.12.2 tag of the repository instead of master.

**Comment by bricechart** [comment] 2021-05-04 10:40
> If you would like to build your local docker then clone https://github.com/openmaptiles/openmaptiles-tools, change the GEOS version variable to 3.9.0 - https://github.com/openmaptiles/openmaptiles-tools/blob/master/docker/postgis/Dockerfile#L11. You can change a tag for your build in https://github.com/openmaptiles/openmaptiles-tools/blob/master/openmaptiles/__init__.py.
> 
> In OMT then you can check, if postgis is using correct GEOS by `make psql` and `SELECT postgis_full_version();`
> 
> On the other hand, if GEOS 3.9.1 is not solving the problem with `TopologyException`, let's downgrade the version of GEOS in https://github.com/openmaptiles/openmaptiles-tools/blob/master/docker/postgis/Dockerfile#L11 and solve this problem before Debian Bullseye is released and bring GEOS 3.9.0 into the base image of Postgis.

When I checked my postgis version, it was not showing the newer GEOS version. I'm starting from scratch with the GEOS 3.9.1 and trying again.

**Comment by bricechart** [comment] 2021-05-10 20:18
Everything seems to be working now with 3.9.1.

**Comment by TomPohys** [comment] 2021-05-31 08:25
Thanks for the discussions. If there are some consequences issues, please create a new issue about that. Thank you all again.

**Closed by TomPohys** 2021-05-31 08:25 UTC
