### ISSUE TITLE
Missing sea fragment in zoom levels 7-9

### ISSUE THREAD

**Issue by rpieciorak** [openmaptiles/openmaptiles#310] opened 2017-07-20 08:49 UTC
Some part of the Baltic sea is missing on zoom levels 7 to 9.
See attached images.

Below zoom level 7:
![zoom6](https://user-images.githubusercontent.com/320136/28408767-dace4dca-6d38-11e7-9528-d8d399f53d4c.png)

Zoom level 7:
![zoom7](https://user-images.githubusercontent.com/320136/28408768-dacf5a8a-6d38-11e7-9ee0-b2d0553c7d16.png)

Above zoom level 9:
![zoom9](https://user-images.githubusercontent.com/320136/28408766-dacb3a0e-6d38-11e7-8e2e-866f86dad714.png)

**Comment by jirik** [comment] 2017-07-20 16:36
Thanks for reporting. The problem is that at Z6 and Z7 we are mixing oceans from NE and lakes from OSM. This sea fragment is considered as a lake in NE and as an ocean in OSM, so it is missing.

Solution is to use OSM oceans also for Z6 and Z7. We need to create two new generalized tables `osm_ocean_polygon_gen5` and `osm_ocean_polygon_gen6` for Z7 and Z6 here:
https://github.com/openmaptiles/import-water/blob/master/import-water.sh#L39

**Comment by nvkelso** [comment] 2017-07-20 18:21
(This will also happen in the Netherlands near Amsterdam and possibly also
in Brazil.)

**Comment by klokan** [comment] 2017-11-14 12:00
Pull request is welcome - or we may need a customer who supports working hours on this effort...

**Comment by stefanb** [comment] 2018-02-28 10:51
For me testing on https://openmaptiles.org/languages/en/#6.03/54.663/19.468
that part of the sea is missing between zoom levels 6 and 8

**Comment by jirik** [comment] 2018-04-16 07:36
Seems to be already fixed in data: https://www.openstreetmap.org/relation/8140878

**Closed by jirik** 2018-04-16 07:36 UTC
Labels: bug, enhancement, help wanted
