### ISSUE TITLE
Death Valley National Park missing from California generated map

### ISSUE THREAD

**Issue by nnhubbard** [openmaptiles/openmaptiles#509] opened 2018-10-11 19:45 UTC
When using the `quickstart.sh` script with `california`, Death Valley National Park does not get created as landuse. Looking at the data using tileserver-gl it appears there is no data imported at all for that National Park.

Nothing seems different about the tags on openstreetmap.org, so I am confused as why it won't import.

It seems to happen at all zoom levels.

![screen shot 2018-10-11 at 12 43 02 pm](https://user-images.githubusercontent.com/30858/46829722-5f522a00-cd53-11e8-8272-7caf7e859bd6.png)

![screen shot 2018-10-11 at 12 43 25 pm](https://user-images.githubusercontent.com/30858/46829746-76911780-cd53-11e8-8b7e-02bf81608e13.png)

**Comment by typebrook** [comment] 2018-10-12 06:40
Be aware that default setting in `quickstart.sh` only generate tiles with zoom levels 0~7 for quick demo.

if you read the mapping chart, it indicates that landuse data only import when z >= 9
https://github.com/openmaptiles/openmaptiles/blob/master/layers/landuse/README.md

**Comment by nnhubbard** [comment] 2018-10-12 15:46
> Be aware that default setting in quickstart.sh only generate tiles with zoom levels 0~7 for quick demo.

Yes, I have used this script for quite some time and changed the default settings to zoom level 14 long ago. This isn't the issue.

> if you read the mapping chart, it indicates that landuse data from osm only get imported when z >= 9
> https://github.com/openmaptiles/openmaptiles/blob/master/layers/landuse/README.md

Sorry if I wasn't clear. The zoom level isn't the issue. ALL other National Parks and Nature Reservers in California have imported correctly and they show as the expected zoom levels. `Death Valley National Park` is NOT imported on any zoom levels, it is completely non-existant from the map data. During import other National Parks get correctly imported, but this does not.

**Comment by nnhubbard** [comment] 2018-10-12 18:56
> Seems like national park belongs to layer [`park`](https://github.com/openmaptiles/openmaptiles/tree/master/layers/park)
> 
> Does it locates in database? check it by scripts like:
> 
> ```
> make psql
> SELECT osm_id FROM osm_park_polygon WHERE first_name = 174732;
> ```

Can you query an `.mbtiles` file like that? I tried and I just get the error:

> no such table: osm_park_polygon: SELECT osm_id FROM osm_park_polygon WHERE first_name = 174732;

Browsing the structure, there is no table called `osm_park_polygon`.

**Comment by nnhubbard** [comment] 2018-10-12 19:00
I have used MapTiler and also tileserver-gl to view the .mbtiles file and see the data. I can clearly see there is no data for `Death Valley National Park`, although other National Parks are there.

**Comment by typebrook** [comment] 2018-10-13 01:42
Well, sorry if I wasn't clear, I mean that you should check PostGis, not the final work (.mbtiles)

openmaptiles roughly use these two steps to generate vector tiles:
1. use `imposm3` to import raw osm data (osm.pbf) into PostGis, using mapping file (.yaml) to define several tables and there generalized copies.
2. use PostGis to generate vector tiles

and we need to check the problem is in `importing` or `generating`

since we keep volume for PostGis 
https://github.com/openmaptiles/openmaptiles/blob/81f75714baac2ef6c518c280005adcbaf6566672/quickstart.sh#L280-L283
we still can launch it again by
`make psql`
and check Death Valley National Park (relation 174732) has been imported into PostGis correctly by 
`SELECT osm_id FROM osm_park_polygon WHERE first_name = 174732;`

**Comment by nnhubbard** [comment] 2018-10-14 04:52
Thanks for explaining. I used `SELECT osm_id FROM osm_park_polygon WHERE first_name = 174732;` and I got the error:

> ERROR:  column "first_name" does not exist

However, I then used `SELECT osm_id FROM osm_park_polygon;` to show the list of IDs and `1747321 is not one of the IDs.

**Comment by typebrook** [comment] 2018-10-14 13:40
Then the problem should be import.

Because you mentioned
>During import other National Parks get correctly imported, but this does not.

So I presume that auto-generated mapping file (`build/mapping.yaml`) has no problem here.
And I guess Death Valley National Park ([relation 174732](https://www.openstreetmap.org/relation/174732#map=9/36.4962/-117.1388)) has no tag issue because it really matches `leisure=nature_reserve`

Please check your osm raw data by tools like `gdal`, make sure Death Valley National Park is **really** inside it.
you can use command like:
`ogrinfo [yourdata].osm.pbf -sql "select * from multilinestrings where osm_id=174732"`

replace `multilinestrings` with `multipolygons` or `other_relations` to search every tables contain relations ([ref](https://www.gdal.org/drv_osm.html))

if it is, then I guess this issue should be reported to [imposm](https://github.com/omniscale/imposm3), not here.

**Comment by nnhubbard** [comment] 2018-10-14 23:17
I am trying to use `gdal` with the command you gave, but I get this error:

> ERROR 1: Type mismatch or improper type of arguments to = operator.

**Comment by typebrook** [comment] 2018-10-15 00:41
`Feature Count: 0` means there is no matched osm objects.
how about `multipolygons` and `other_relations`? 
If there still has no matched data, then its the problem of your raw data

**Comment by nnhubbard** [comment] 2018-10-15 04:00
Both of those both have `Feature Count: 0`, so it looks like for some reason they are not in the `.osm.pbf` file. Using `./quickstart.sh california`, that pulls the `.osm.pbf` from `geofabrik`, so it seems they somehow are not including that data. 

The interesting thing is, I tested the `us_west` download, and that does include the data using: `ogrinfo california-latest.osm.pbf -sql "select * from multipolygons where osm_id = '174732'";`.

**Comment by typebrook** [comment] 2018-10-15 04:49
Then this is not related to openmaptiles, you can **close** this issue now.

Check daily extraction for California always misses this relation.
If so, you may report this issue to `geofabrik`, maybe it is an error, or maybe they intends to do this with good reason?

If you still have question about this problem, it's welcome to contact me by typebrook@gmail.com:blush:

**Comment by nnhubbard** [comment] 2018-10-15 15:42
I heard back from Frederik Ramm from `Geofabrik`. Here is what he said:

> The relation is also in the California file, however there's apparently
> a little bit in Nevada that is part of the national park:
> https://www.openstreetmap.org/way/125420571 This bit is not in the
> california-latest file, and it seems that OGR then decides that it
> cannot build the polygon *at all* (instead of building the main region
> and being happy with it).

So, the data IS in the `.osm.pbf` file, which means the problem is elsewhere. Where else should I look to solve this issue?

**Comment by typebrook** [comment] 2018-10-15 16:39
Then its your turn to research, try to make it really be imported in PostGIS by adjusting `imposm3` mapping file

Please read [imposm doc](https://imposm.org/docs/imposm3/latest/mapping.html#type) carefully, and try to modify current mapping : 
https://github.com/openmaptiles/openmaptiles/blob/ff99a02aae287ed0546abe705c981e71c8618c33/layers/park/mapping.yaml#L53-L75

**Comment by nnhubbard** [comment] 2018-10-15 16:48
I just wonder if this is a bigger issue where other extracts have the same issue and are missing important data.

**Comment by nnhubbard** [comment] 2018-10-16 19:42
@typebrook How would changing the mapping file fix this issue?

**Comment by MartinMikita** [comment] 2018-10-18 07:11
According to the answer from geofabrik:
> This **bit is not in** the `california-latest` file, and it seems that OGR then decides that it
cannot build the polygon at all

This is not a problem of OpenMapTiles, but the problem of missing data in partial regions.
As this is not a problem with a planet, we do not think it would be easy to fix this via mapping or modifying `imposm3` utility.

Therefore, we are closing this ticket as not a bug on our side.

**Closed by MartinMikita** 2018-10-18 07:11 UTC
