### ISSUE TITLE
Rendering labels cut-off

### ISSUE THREAD

**Issue by mpaine-act** [openmaptiles/openmaptiles#628] opened 2019-05-20 16:01 UTC
When I render OSM maps, I see various location labels cut-off

https://imgur.com/a/dUKGyWX

Is this a known issue that can be fixed easily?  It happens at all zoom levels, although the further zoomed in, the less the problem is visible (sometimes corrected).

**Comment by chebourne** [comment] 2019-08-05 15:34
Duplicate of #347 

As far as I know this has never been resolved for raster maps.

I now try and use vector maps as much as possible in my applications so that this problem does not crop up.

**Comment by eva-j** [comment] 2019-11-06 16:47
Duplicate of https://github.com/openmaptiles/openmaptiles/issues/224.

**Closed by eva-j** 2019-11-06 16:47 UTC
