### ISSUE TITLE
error generating some tile

### ISSUE THREAD

**Issue by fabriziopicconi** [openmaptiles/openmaptiles#1615] opened 2024-01-16 18:36 UTC
reproduce problem with command
./quickstart.sh italy
(MAX_ZOOM=14)
error:
Verifying pgquery data source by retrieving a tile at [14,9268,3575] from postgres:5432/openmaptiles...
a tile at [14,9268,3575] from postgres:5432/openmaptiles was generated in 127ms.  The result is 390 bytes detected as gzipped data. 367 bytes uncompressed.
Test tile begins with 1a. This byte often corresponds to a valid vector tile.
[9m 18.5s]  14.4671%  80.6k/557.4k @  145/s | ✓ 80.6k □ 0 | 54m 59.0s leftError getting 14/8695/5936: error: invalid input syntax for type integer: ""
[9m 20.8s]  14.5362%  81.0k/557.4k @  145/s | ✓ 81.0k □ 0 | 54m 54.0s leftError getting 14/8695/5936: error: invalid input syntax for type integer: ""
[9m 25.1s]  14.6687%  81.8k/557.4k @  145/s | ✓ 81.8k □ 0 | 54m 45.0s leftPossible callback crash for 14/8695/5936: error: invalid input syntax for type integer: ""
[9m 59.1s]  15.7845%  88.0k/557.4k @  147/s | ✓ 88.0k □ 0 | 53m 15.0s leftError getting 14/8584/5899: error: invalid input syntax for type integer: ""
[10m 1.4s]  15.8690%  88.5k/557.4k @  147/s | ✓ 88.5k □ 0 | 53m 6.0s leftError getting 14/8584/5899: error: invalid input syntax for type integer: ""
[10m 5.6s]  16.0139%  89.3k/557.4k @  147/s | ✓ 89.3k □ 0 | 52m 54.0s leftPossible callback crash for 14/8584/5899: error: invalid input syntax for type integer: ""
[12m 9.8s]  20.6196% 114.9k/557.4k @  158/s | ✓ 114.9k □ 0 | 46m 47.0s leftError getting 14/8760/6088: error: invalid input syntax for type integer: ""
[12m 12.4s]  20.7126% 115.5k/557.4k @  158/s | ✓ 115.5k □ 0 | 46m 41.0s leftError getting 14/8760/6088: error: invalid input syntax for type integer: ""
[12m 17.1s]  20.8342% 116.1k/557.4k @  158/s | ✓ 116.1k □ 0 | 46m 39.0s leftPossible callback crash for 14/8760/6088: error: invalid input syntax for type integer: ""
[41m 48.0s]  99.9946% 557.4k/557.4k @  222/s | ✓ 557.4k □ 0 | 0.0s left2024-01-16 18-10-24 Tile generation complete!

**Comment by TomPohys** [comment] 2024-02-15 08:46
Thanks for the issue, this is probably a duplicate of https://github.com/openmaptiles/openmaptiles/issues/1583.

**Closed by TomPohys** 2024-02-15 08:46 UTC
