### ISSUE TITLE
Khmer font rendering issue

### ISSUE THREAD

**Issue by sophalch** [openmaptiles/openmaptiles#319] opened 2017-08-16 03:48 UTC
Khmer font is not rendered correctly. As shown in the left picture:
- there is a plus symbol instead of subscript
- vowel is not in the right position

![khmer-font-issue](https://user-images.githubusercontent.com/8021598/29346337-edb77858-8287-11e7-93cb-73dbb292370b.png)

If it helps, this is the same issue with mapnik a few years ago:
https://github.com/mapnik/mapnik/issues/1208

**Comment by jirik** [comment] 2017-08-17 12:10
@klokan Is it possible to be the same problem as in case of #194 ?

**Comment by jirik** [comment] 2017-08-17 12:10
@sophalch Thanks for reporting!

**Comment by sophalch** [comment] 2017-08-27 23:30
The text is appearing correctly in inspect mode. Does that mean it's not openmaptiles issue?

![image](https://user-images.githubusercontent.com/8021598/29754962-42fe760a-8bd3-11e7-8ee1-6d4c9ba2bda2.png)

**Comment by klokan** [comment] 2017-08-27 23:41
OpenMapTiles vector tiles contain probably a correct Unicode string.

Please try to use the map with a font which for sure contains all the glyphs - such as https://www.google.com/get/noto/#sans-khmr downloaded TrueType.

Either it is a problem with the font or with the Mapbox GL font rendering implementation.
(OpenLayers viewer would probably display the label correctly - as it is using web browser for font rendering).

It may be a similar problem with our KlokanTech Noto font as described in #194.

Please test and report what you have discovered...

**Comment by sophalch** [comment] 2017-08-28 01:24
Thanks @klokan,

As you suspected, this is Mapbox GL issue.

Details:
- Changing font to Noto Sans Khmer doesn't fix the issue
- Following the example here https://openmaptiles.org/docs/website/openlayers/, and the text is rendered correctly in openlayer.
![image](https://user-images.githubusercontent.com/8021598/29755944-a51264a0-8be2-11e7-9231-3b6534a45dd8.png)
- The style used in openlayer is also using Klokantech Noto Sans font, so the font has no issue.

Thanks

**Comment by jirik** [comment] 2017-08-29 07:03
@sophalch Thanks for the report. So I am closing this issue, because it is not caused by OpenMapTiles. I recommend you to open this issue at https://github.com/mapbox/mapbox-gl-js

**Closed by jirik** 2017-08-29 07:03 UTC
