### ISSUE TITLE
Downloading Asia street map fails 

### ISSUE THREAD

**Issue by mohammadumar29** [openmaptiles/openmaptiles#449] opened 2018-04-26 11:43 UTC
I am trying to download open street map of Asia from following link
https://openmaptiles.com/downloads/tileset/osm/asia/

The download completed but file downloaded was corrupt. I opened the file using SqlLite browser it gives error " database disk image is malformed: select * from map limit 10".
![image](https://user-images.githubusercontent.com/11807976/39347161-0c2f4c2a-4a0b-11e8-888e-1f994c261193.png)
I downloaded the data second time but same error.

I have also checked the MD5 value of the downloaded file it does not match with the provided MD5
![image](https://user-images.githubusercontent.com/11807976/39347113-c9718736-4a0a-11e8-847b-181537a17832.png)

**Comment by AliFlux** [comment] 2018-04-27 18:17
I faced a similar issue. Apparently the server timed out after one hour. 

![error](https://user-images.githubusercontent.com/8333794/39378085-c3f3af8a-4a70-11e8-9ade-ebbf834c03ea.PNG)

Is it because the download link is only valid for one hour? And that the download has to be completed within that one hour? Seems pretty unrealistic since in most parts of the world the bandwidth isn't enough to download datasets within a single hour.

**Comment by AliFlux** [comment] 2018-04-27 18:29
I tried downloading a 300mb dataset and it gave this error on 68%. I'll try again and update here.

![2](https://user-images.githubusercontent.com/8333794/39378745-b5402c8c-4a72-11e8-8b5c-48ce74728740.PNG)

**Comment by AliFlux** [comment] 2018-04-27 18:52
Trying it for the third time. It's still giving errors.

![er](https://user-images.githubusercontent.com/8333794/39379827-f6c6cbf4-4a75-11e8-91fb-3d6aa14d0b21.PNG)

**Comment by MartinMikita** [comment] 2018-04-28 16:26
Hello,

The download link is valid for one hour, which means, you can start the download with this link in one hour. But the download can take more hours and this validity is not broken after the download has been started.

The problem is on your side, or on your internet provider.
We have verified the download links, and we are able to download them correctly, even using an internet browser.

For downloading large tilesets ( > 1 GB) you should use a download manager, which is able to continue with partially downloaded content, for an example `wget` utility on Linux.

As this is not the problem on our side, we are not able to fix it for you, therefore we are closing this ticket.

**Closed by MartinMikita** 2018-04-28 16:26 UTC
