### ISSUE TITLE
Metadata contains key/value pair "json" which is incompatible with tileserver.php

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/openmaptiles#379] opened 2017-12-04 19:31 UTC
Just created mbtiles ([tiles.zip](https://github.com/openmaptiles/openmaptiles/files/1528504/tiles.zip)) with a fresh installation of openmaptiles using ./quickstart.sh.

The metadata of this mbtiles file contains a key/value pair "json" which is incompatible with tileserver.php (Error Message: _JSON metadata file is not valid. Please check configuration of your server_):

![image](https://user-images.githubusercontent.com/20856381/33571137-5434f788-d92f-11e7-8338-21648eada3b7.png)

Manually deleting the key/value pair from the metadata table solves this issue. 

Why is this key/value pair in the metadata?

**Comment by daliborjanak** [comment] 2017-12-05 07:54
It is deffinition of layers. It is compatible. Tileserver-php upacked this JSON into TileJSON but It looks like that there is wrong character. Open [tileserver-php-folder]/index.json
```
Error: Parse error on line 1:
...>'name:ar', '') AS "name:ar", NULLIF(tag
-----------------------^
Expecting 'EOF', '}', ':', ',', ']'
```
This filed is wrongly encoded:
``` javascript
"table": "(SELECT geometry, name, name_en, name_de, NULLIF(tags->'name:ar', '') AS \"name:ar\", NULLIF(tags->'name:az', '') AS \"name:az\", NULLIF(tags->'name:be', '') AS \"name:be\", NULLIF(tags->'name:bg', '') AS \"name:bg\", NULLIF(tags->'name:br', '') AS \"name:br\", NULLIF(tags->'name:bs', '') AS \"name:bs\", NULLIF(tags->'name:ca', '') AS \"name:ca\", NULLIF(tags->'name:cs', '') AS \"name:cs\", NULLIF(tags->'name:cy', '') AS \"name:cy\", NULLIF(tags->'name:da', '') AS \"name:da\", NULLIF(tags->'name:de', '') AS \"name:de\", NULLIF(tags->'name:el', '') AS \"name:el\", NULLIF(tags->'name:en', '') AS \"name:en\", NULLIF(tags->'name:eo', '') AS \"name:eo\", NULLIF(tags->'name:es', '') AS \"name:es\", NULLIF(tags->'name:et', '') AS \"name:et\", NULLIF(tags->'name:fi', '') AS \"name:fi\", NULLIF(tags->'name:fr', '') AS \"name:fr\", NULLIF(tags->'name:fy', '') AS \"name:fy\", NULLIF(tags->'name:ga', '') AS \"name:ga\", NULLIF(tags->'name:gd', '') AS \"name:gd\", NULLIF(tags->'name:he', '') AS \"name:he\", NULLIF(tags->'name:hr', '') AS \"name:hr\", NULLIF(tags->'name:hu', '') AS \"name:hu\", NULLIF(tags->'name:hy', '') AS \"name:hy\", NULLIF(tags->'name:is', '') AS \"name:is\", NULLIF(tags->'name:it', '') AS \"name:it\", NULLIF(tags->'name:ja', '') AS \"name:ja\", NULLIF(tags->'name:ja_kana', '') AS \"name:ja_kana\", NULLIF(tags->'name:ja_rm', '') AS \"name:ja_rm\", NULLIF(tags->'name:ka', '') AS \"name:ka\", NULLIF(tags->'name:kk', '') AS \"name:kk\", NULLIF(tags->'name:kn', '') AS \"name:kn\", NULLIF(tags->'name:ko', '') AS \"name:ko\", NULLIF(tags->'name:ko_rm', '') AS \"name:ko_rm\", NULLIF(tags->'name:la', '') AS \"name:la\", NULLIF(tags->'name:lb', '') AS \"name:lb\", NULLIF(tags->'name:lt', '') AS \"name:lt\", NULLIF(tags->'name:lv', '') AS \"name:lv\", NULLIF(tags->'name:mk', '') AS \"name:mk\", NULLIF(tags->'name:mt', '') AS \"name:mt\", NULLIF(tags->'name:nl', '') AS \"name:nl\", NULLIF(tags->'name:no', '') AS \"name:no\", NULLIF(tags->'name:pl', '') AS \"name:pl\", NULLIF(tags->'name:pt', '') AS \"name:pt\", NULLIF(tags->'name:rm', '') AS \"name:rm\", NULLIF(tags->'name:ro', '') AS \"name:ro\", NULLIF(tags->'name:ru', '') AS \"name:ru\", NULLIF(tags->'name:sk', '') AS \"name:sk\", NULLIF(tags->'name:sl', '') AS \"name:sl\", NULLIF(tags->'name:sq', '') AS \"name:sq\", NULLIF(tags->'name:sr', '') AS \"name:sr\", NULLIF(tags->'name:sr-Latn', '') AS \"name:sr-Latn\", NULLIF(tags->'name:sv', '') AS \"name:sv\", NULLIF(tags->'name:th', '') AS \"name:th\", NULLIF(tags->'name:tr', '') AS \"name:tr\", NULLIF(tags->'name:uk', '') AS \"name:uk\", NULLIF(tags->'name:zh', '') AS \"name:zh\", NULLIF(tags->'name_int', '') AS \"name_int\", NULLIF(tags->'name:latin', '') AS \"name:latin\", NULLIF(tags->'name:nonlatin', '') AS \"name:nonlatin\", class FROM layer_waterway(!bbox!, z(!scale_denominator!))) AS t",
```
I have to look at that deeply

**Comment by pathmapper** [comment] 2017-12-05 08:40
@daliborjanak maybe the cause are all the colons for **name:**

![image](https://user-images.githubusercontent.com/20856381/33597434-b5c622a4-d99f-11e7-8029-e146608b1a47.png)


I wonder why I can't reproduce what you've posted:

`[tileserver-php-folder]/index.json `

shows a 404

and

`[tileserver-php-folder]/tileserver.php/index.json`

shows no error like you posted above, the result looks valid (screenshot above).

**Comment by jirik** [comment] 2017-12-05 10:00
TileServer-PHP has a problem is with double quotation marks in [`"Layer"/"Datasource"/"table"`](https://gist.github.com/jirik/3fababd72226bf483688cad2b44063c5#file-json-json-L54) fields in `json`'s value.

@daliborjanak I am not sure if it fails in [tileserver.php#L633](https://github.com/klokantech/tileserver-php/blob/master/tileserver.php#L633) or later. If the L633 is the problem, it should be unescaped in a better way then now (since the `json`'s value is correct JSON). If the problem is later, you can try one of following options:
- to delete the whole `"Layer"` key from the `json`. The remaining keys would be [`"_prefs"`](https://gist.github.com/jirik/3fababd72226bf483688cad2b44063c5#file-json-json-L548) and [`"vector_layers"`](https://gist.github.com/jirik/3fababd72226bf483688cad2b44063c5#file-json-json-L555)
- to delete only `"Layer"/"Datasource"/"table"` keys from the `json`
- to remove double quotations marks from  `"Layer"/"Datasource"/"table" fields, but this breaks SQL syntax of the query

**Comment by daliborjanak** [comment] 2017-12-05 12:26
Let's remove "Layer". We are removing it in download service. We are leaving only "vector_layers" in json field

**Comment by nirvine** [comment] 2018-01-28 10:55
Has this issue been addressed? I am having trouble with "JSON metadata is not valid" error (klokantech/tileserver-php#116), and that issue references this.  
Apologies if I should not have asked here!

**Comment by vitjazzz1983** [comment] 2018-01-28 12:28
hi there! same trouble: "JSON metadata file is not valid. Please check configuration of your server".
Wamp Version 3.1.0 - 64bi

**Comment by pathmapper** [comment] 2018-01-28 12:38
@nirvine @vitjazzz1983 This is not fixed until now, but if your issues are also related to the value of the json key in the metadata of the .mbtiles file, you are able to workaround by deleting the value or the whole key/value pair from the metadata table.
For this task you could use e.g. http://sqlitebrowser.org/ or this Firefox plugin https://addons.mozilla.org/de/firefox/addon/sqlite-manager/

**Comment by nirvine** [comment] 2018-01-28 19:58
Using DB Browser for Sqlite I deleted the json metadata - "set field to NULL), and it has fixed the error.
Many thanks.

**Comment by vitjazzz1983** [comment] 2018-01-28 20:13
**@pathmapper** thank’s!

**Comment by daliborjanak** [comment] 2018-02-19 14:57
Fixed in master now

**Closed by daliborjanak** 2018-02-19 14:57 UTC

**Comment by pathmapper** [comment] 2018-02-23 15:26
Thanks @daliborjanak !
