### ISSUE TITLE
Integrity CI fails with indecipherable error message

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1496] opened 2023-02-18 03:38 UTC
The integrity CI currently fails in all case.
The error messages in the console are not helpful in troubleshooting the problem.

I've also opened #1495 in order to provide a script matching what this CI does in order to help with present and future troubleshooting.

**Comment by wcedmisten** [comment] 2023-02-25 16:31
Could it be related to this?

https://github.com/openmaptiles/openmaptiles/issues/1498

I see a similar `current transaction is aborted` error when I run the integrity script locally and in these logs: https://github.com/openmaptiles/openmaptiles/actions/runs/4209376803/jobs/7306310129#step:6:4253

Admittedly, the error doesn't include details about the first transaction which was aborted, so I can't tell if the root error is the same. But it does seem like the issue is coming from the `make import-diff` step.

**Comment by darren1713** [comment] 2023-02-25 16:49
@wcedmisten I posted the issue you referenced #1498 and I found the index that generated this issue by looking through /var/log/postgresql logs to find the very first command that failed. It's a monster log, I specifically had to roll back through ~900,000 lines of logs to find the first command that failed.

Or have a quick grep through your postgresql logs for "osm_route_member_network_ref_idx". That was the index that caused the failure for me.

I also posted a lot more info on the other ticket here: https://github.com/omniscale/imposm3/issues/288

Would be great if you are also seeing the same issue and can confirm.

**Comment by wcedmisten** [comment] 2023-02-25 18:37
How are you finding that log in `/var/log/postgresql`? I've looked in both the persistent Postgres container `zelonewolf-openmaptiles_postgres_1` and the ephemeral `diff-import` container `zelonewolf-openmaptiles_openmaptiles-tools_run_b11b1985430e` and neither seem to have a logfile.

Am I looking in the wrong place?

I also noticed that both of these have postgres's `log_statement` set to `none`:

```
$ psql -c "SHOW log_statement";
 log_statement 
---------------
 none
(1 row)
```

**Comment by wcedmisten** [comment] 2023-02-25 20:14
Update on this: although I couldn't find the logs showing the offending Postgres error, I ran the `integrity.sh` script on the the [commit in question](bc9bbd2e67bb90163b9e85789c89fd4d87561b8d) and the [previous commit](efa6b27fba105f06614322a8374ae8c42075b1d8), and found that only the new commit including the route de-duplicating index has this issue.

I'm not sure why the CI passed for this commit, and then started failing later https://github.com/openmaptiles/openmaptiles/actions/runs/4016490711/jobs/6899588772.

Is it possible the data causing the issue (duplicate routes) was only added to this OSM extract (Monoco) recently? Seems a bit unlikely, but maybe plausible.

**Comment by darren1713** [comment] 2023-02-25 23:21
@wcedmisten I have a bit of a unique configuration where I'm running postgres on the "host" and making the docker images connect to the postgres server on the host. I wouldn't suggest doing this, it requires building a few extra modules / postgis / etc.

A much easier test here would be to just revert that one commit (#1361) from your build and run again. If the issue is fixed, it's very likely the same issue I saw.

**Comment by ZeLonewolf** [comment] 2023-02-26 00:27
There are only two route relations total in Monaco:
https://overpass-turbo.eu/s/1rM9

https://www.openstreetmap.org/relation/3445894
https://www.openstreetmap.org/relation/9716363

Both are years old.

**Comment by ZeLonewolf** [comment] 2023-02-26 00:28
> Or have a quick grep through your postgresql logs for "osm_route_member_network_ref_idx". That was the index that caused the failure for me.

Does that index need to be changed in some way?

**Comment by darren1713** [comment] 2023-02-26 14:23
> > Or have a quick grep through your postgresql logs for "osm_route_member_network_ref_idx". That was the index that caused the failure for me.
> 
> Does that index need to be changed in some way?

Oh just to be clear, I have no idea why that index isn't working, or is incorrect, just that it is the source of my failure and I've noted which patch added that index so the maintainers of this project can review. I am not a maintainer of the project.

**Comment by wcedmisten** [comment] 2023-02-26 15:09
I'm still not sure why this issue only appeared much later than the PR was merged, but reverting the commit that added that index did allow the Integrity job to pass:

https://github.com/openmaptiles/openmaptiles/actions/runs/4275499555/jobs/7442918080

**Comment by ZeLonewolf** [comment] 2023-02-26 15:18
Thanks! I added that index so now I've got a starting point to troubleshoot. I'm still not sure what's broken but at least I can explore alternatives that don't blow up.

**Comment by darren1713** [comment] 2023-02-27 14:01
> Thanks! I added that index so now I've got a starting point to troubleshoot. I'm still not sure what's broken but at least I can explore alternatives that don't blow up.

Thanks for looking into this. Just to post a quick reminder here about a secondary failure that I caused me to open this ticket, I had failures in imposm3 diff updates, when differential updates were being inserted into the database. That issue is here: https://github.com/omniscale/imposm3/issues/288

**Closed** 2023-03-06 16:10 UTC
