### ISSUE TITLE
running quickstart: connection refused error (.osm.pbf -> imposm3 -> PostgreSQL)

### ISSUE THREAD

**Issue by andre82er** [openmaptiles/openmaptiles#163] opened 2017-02-01 22:43 UTC
Hi,
I am trying to run quickstart.sh, but I keep running into this error:
_====> : Start importing OpenStreetMap data: ./data/albania.osm.pbf -> imposm3[./build/mapping.yaml] -> PostgreSQL
      : Imposm3 documentation: https://imposm.org/docs/imposm3/latest/index.html 
      :   Thank you Omniscale! 
      :   Source code: https://github.com/openmaptiles/import-osm 
      : The OpenstreetMap data license: https://www.openstreetmap.org/copyright (ODBL) 
      : Thank you OpenStreetMap Contributors ! 
The MIN_ZOOM variable is not set. Defaulting to a blank string.
The MAX_ZOOM variable is not set. Defaulting to a blank string.
The BBOX variable is not set. Defaulting to a blank string.
Importing in normal mode
[Feb  1 21:55:46] **dial tcp 127.0.53.53:5432: getsockopt: connection refused**_

Here is the first part from the log file:
_====> : OpenMapTiles quickstart! [ https://github.com/openmaptiles/openmaptiles ]    
      : This will be logged to the ./quickstart.log file (for debugging) and to the screen
      : Area             : albania 
      : Git version      : 4bb581fc282d9c6425968d9fd5386d08abab1659 
      : Started          : 2017-02-01T22:39+01:00 
      : Your bash version: 4.3.42(1)-release
      : Your OS          : linux-gnu
Docker version 1.11.0, build 4dc5990
docker-compose version 1.10.0, build 4bd6f1a
: This is working on x86_64 ; Your kernel is:
4.4.0-21-generic
x86_64
      : --- Memory, CPU info ---- 
system memory (GB): 3.7480  
SwapTotal:       4551676 kB
cpu number: 4 x bogomips : 3392.03
MemFree:         2341720 kB
SwapFree:        4551676 kB
CmaFree:               0 kB
HugePages_Free:        0_

I haven't found a solution to this problem. For solutions I would be very grateful.

**Comment by ImreSamu** [comment] 2017-02-01 23:09
> I haven't found a solution to this problem. For solutions I would be very grateful.

* Can you  create a new [gist]( https://gist.github.com/)  from your `./quickstart.log`  ?  
* It is Linux host  (  or  Mac or Windows )  ?

**Comment by andre82er** [comment] 2017-02-02 10:52
Thanks for the fast respond.
Yes, it is Linux host (Ubuntu 16.04 Xenial).
I have attached the quickstart.log.

[quickstart.log.txt](https://github.com/openmaptiles/openmaptiles/files/747478/quickstart.log.txt)

**Comment by ImreSamu** [comment] 2017-02-02 15:28
strange ..
* it is working on the [.travis test](https://travis-ci.org/openmaptiles/openmaptiles)
  *  `Docker version 1.10.0, build 590d5108`
  *  `docker-compose version 1.7.1, build 0a9ab35`
  *  `system memory (GB): 7.3056` 
* and I have retested - and working on my machine ..  
  * `Docker version 1.13.0, build 49bf474`
  * `docker-compose version 1.10.0, build 4bd6f1a`
  * `system memory (GB): 7.5968`

But we don't tested with 4G RAM  ( your:  `system memory (GB): 3.7480` )

Maybe your  `openmaptiles_postgres`  ( PostgreSQL service )  is stopped ?   ( **No disk space** ?  No memory?)

After re-running the `./quickstart.sh`  ( no browser , no other running  programs ) 
What is the output of 
* `docker ps` 
* `docker ps -a`

I would like to know,   that `openmaptiles_postgres` is running or stopped 

Can you verify the **disk space** on your docker libs ?  
*  `df -h /var/lib/docker/`

Can you post the `openmaptiles_postgres`  logs ?  ( please create a `txt` file )
*  `docker logs openmaptiles_postgres_1`

**Comment by andre82er** [comment] 2017-02-06 16:29
Dear ImreSamu,

the .txt file contains the desired information:
[docker_pg_test.txt](https://github.com/openmaptiles/openmaptiles/files/755210/docker_pg_test.txt)

I moved the pg directory of my local pg installation from /var/lib/postgresql (/dev/sda6) to /home/... (/dev/sda5). Could this cause the error?

**Comment by ImreSamu** [comment] 2017-02-06 18:14
>the .txt file contains the desired information:

thank you,
*  the `openmaptiles/postgis:2.3`  is running,  so I don't know what is the root cause.  And why is the connection refused ...  



>I moved the pg directory of my local pg installation from /var/lib/postgresql (/dev/sda6) to /home/...
> (/dev/sda5). Could this cause the error?

I am not sure , but maybe not. 

### Some new test cases:

#### docker upgrade 

Can you upgrade your `docker` to the latest version ? From  `v1.11`  to  [v1.13.0](https://github.com/docker/docker/releases/tag/v1.13.0)
*  I would like to test -  if it is a docker related network error or not  :  https://github.com/docker/docker/search?q=getsockopt%3A+connection+refused&type=Issues&utf8=%E2%9C%93

#### more disk space 

Can you create a little more free space in `/dev/sda6`  ( `/var/lib/docker/` )

**Comment by andre82er** [comment] 2017-02-07 10:48
I upgraded docker from 1.11 to 1.13 (1.13 was the version I originally came from) and increased the available memory to 23.7 GB before running quickstart.sh. Unfortunately, nothing has changed.
[docker_pg_test_1_13.txt](https://github.com/openmaptiles/openmaptiles/files/757311/docker_pg_test_1_13.txt)

**Comment by ImreSamu** [comment] 2017-02-07 14:34
Thank you! 




Are you using some special firewall or network config ? 

Are you installed all recommended extra packages ?
 *  https://docs.docker.com/engine/installation/linux/ubuntu/#/recommended-extra-packages

Please clean your docker environment
*   `docker-compose down`
*   `docker system prune`  -   But be careful ,  And check the docker docs ! 
```
$ docker system prune
WARNING! This will remove:
	- all stopped containers
	- all volumes not used by at least one container
	- all networks not used by at least one container
	- all dangling images
Are you sure you want to continue? [y/N] 
```

#### big testcase 
Can you  re-test  with clean install ? 

```
git clone https://github.com/openmaptiles/openmaptiles.git
cd openmaptiles
./quickstart.sh

# And please attach the output of this commands 
docker stats --no-stream
df -h /var/lib/docker/
docker ps
docker ps -a
docker info
docker version
docker network list
docker network inspect  openmaptiles_default
docker logs -t  openmaptiles_postgres_1
docker inspect openmaptiles_postgres_1
make psql-list-tables

docker-compose run import-osm
docker stats --no-stream
docker ps -a
docker logs -t  openmaptiles_import-osm_run_1
docker inspect  openmaptiles_import-osm_run_1
git status
```
( And please attach the current  `./quickstart.log` )

**Comment by ImreSamu** [comment] 2017-02-07 21:47
I have tested in the cloud,  
and the `./quickstart.sh` is working with 2Gb RAM  ( `system memory (GB): 1.9560` )  ;

**Comment by andre82er** [comment] 2017-02-07 23:45
Dear ImreSamu,
many thanks for your great commitment.

I did:
sudo apt-get install curl \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual

But:
linux-image-extra-4.4.0-21-generic is already the newest version (4.4.0-21.37).
curl is already the newest version (7.47.0-1ubuntu2.2).
The following packages have unmet dependencies:
linux-image-extra-virtual : Depends: linux-image-generic (= 4.4.0.62.65) but it is not going to be installed




[docker_big_test.txt](https://github.com/openmaptiles/openmaptiles/files/759317/docker_big_test.txt)
[quickstart.log.txt](https://github.com/openmaptiles/openmaptiles/files/759318/quickstart.log.txt)

**Comment by Sacro** [comment] 2017-02-07 23:52
By the response of 127.0.53.53 it looks like you're trying to connect using a hostname that doesn't belong to you and ICANN is warning you of it.

Either switch to a hostname (and relevant DNS) that you control, or use the straight IP (or add it to your hosts file)

https://www.icann.org/news/announcement-2-2014-08-01-en

**Comment by ImreSamu** [comment] 2017-02-10 15:26
Thanks @Sacro  ,  I agree, probably a DNS network problem ..

@andre82er 
Thank you for your test data ...
My problem :  I can't replicate ...

And as I see some containers can see the database server - but some not :
can you check ?
```
docker-compose run --rm import-osmborder      ping postgres -c3
docker-compose run --rm import-natural-earth  ping postgres -c3
docker-compose run --rm import-lakelines      ping postgres -c3
docker-compose run --rm import-osm            ping postgres -c3
docker-compose run --rm import-sql            ping postgres -c3
docker-compose run --rm openmaptiles-tools    ping postgres -c3
```

In the https://docs.docker.com/engine/installation/linux/linux-postinstall/ page there are some DNS related topic,

**Comment by andre82er** [comment] 2017-02-11 16:19
@Sacro: Thanks for the hint!

@ImreSamu: Here is the ping test: 
[docker ping.txt](https://github.com/openmaptiles/openmaptiles/files/768607/docker.ping.txt)

Unfortunately, the post-installation steps for Linux have not helped. I think it's time for a fresh Linux installation.

**Comment by ImreSamu** [comment] 2017-02-16 20:13
@andre82er 
Thanks,

the ping is ok.
A strange GoLang problem ?   https://github.com/docker-library/golang/issues/109
I hope it is fixed in the Go1.8 

> I think it's time for a fresh Linux installation.

Sorry,   some problems not so easy to solve ..

**Closed** 2017-03-22 13:01 UTC
